/* Generated By:JavaCC: Do not edit this line. DTextCompilerConstants.java */
package info.beastarman.e621.api.dtext;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DTextCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAGOPEN = 1;
  /** RegularExpression Id. */
  int TAGCLOSE = 2;
  /** RegularExpression Id. */
  int BRACESOPEN = 3;
  /** RegularExpression Id. */
  int BRACESCLOSE = 4;
  /** RegularExpression Id. */
  int SLASH = 5;
  /** RegularExpression Id. */
  int BACKSLASH = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int PIPE = 8;
  /** RegularExpression Id. */
  int QUOTE = 9;
  /** RegularExpression Id. */
  int TWODOTS = 10;
  /** RegularExpression Id. */
  int HASHTAG = 11;
  /** RegularExpression Id. */
  int AT = 12;
  /** RegularExpression Id. */
  int ASTERISKS = 13;
  /** RegularExpression Id. */
  int SPACE = 14;
  /** RegularExpression Id. */
  int NEWLINE = 15;
  /** RegularExpression Id. */
  int URL = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int TAGNAME = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"/\"",
    "\"\\\\\"",
    "\"=\"",
    "\"|\"",
    "\"\\\"\"",
    "\":\"",
    "\"#\"",
    "\"@\"",
    "<ASTERISKS>",
    "<SPACE>",
    "<NEWLINE>",
    "<URL>",
    "<NUMBER>",
    "<TAGNAME>",
  };

}
